Updated to 1.18.1 (Fabric only)
RakambdaOrg/EditSign pull request #80
Opened 2021-12-12 00:50 UTC by tyleraharrison

Could not get Forge to pull the new version from servers, don't merge this until that is fixed 🤣

2021-12-12 07:25 UTC, RakSrinaNa commented on gradle.properties
> -mappings_version=1.18
This should be just `1.18.1`. 
What you changed here are the mappings for forge. This is probably why you didn't managed to get Forge working.

2021-12-12 07:31 UTC, RakSrinaNa requested changes

2021-12-12 07:31 UTC, RakSrinaNa commented on gradle/libs.versions.toml
> -cloth-config-forge-version = "6.0.43"
This also has to be changed in the forge's build.gradle. `fg.deobf` doesn't support versions catalog so it is duplicated there.

2021-12-12 07:47 UTC, RakSrinaNa commented
As an example this is [what it looks like](https://github.com/RakSrinaNa/FallingTree/pull/261) on one of my other mods (which is made the same way) 😉 

Also, can you target the 1.18.1 branch please.

2021-12-13 04:38 UTC, tyleraharrison commented
> As an example this is [what it looks like](https://github.com/RakSrinaNa/FallingTree/pull/261) on one of my other mods (which is made the same way) 😉 
> 
> Also, can you target the 1.18.1 branch please.

If I had the time I would, I worked to get my server ported over for my campus but now I'm floored with work. Feel free to scrap my code or use it for reference

2021-12-13 07:23 UTC, RakSrinaNa approved these changes

2021-12-13 07:24 UTC, merged